version: 2.1
orbs:
  service-orb: woshizzy/service-base@volatile

workflows:
  all-workflows:
    jobs:
      - service-orb/test:
          name: test
          context: org-global
          DB_NAME: articles_test
      - docker_approval:
          type: approval
          requires:
            - test
      - service-orb/build:
          name: build_images
          context: org-global
          SERVICE_NAME: articles-service
          requires:
            - docker_approval
      - service-orb/push:
          name: push_images
          context: org-global
          requires:
            - build_images
