apiVersion: apps/v1beta2
kind: Deployment
meatadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Realease.Name }}
    tag: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      restartPolicy: Always
      containers:
        - image: zengzhiyuan/articles-service-core:{{ .Values.image.tag }}
          name: {{ .Chart.Name }}
          env:
            - name: RABBIT_SERVER
              value: guest-rabbitmq
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_USER
              value: user
            - name: RABBITMANAGEMENT_PORT
              value: "15672"
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: guest-rabbitmq
                  key: rabbitmq-password
            - name: DB_SERVER
              value: root-mysql
            - name: DB_NAME
              value: articles
            - name: DB_USER
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: root-mysql
                  key: mysql-root-password
