apiVersion: apps/v1beta2
kind: Deployment
meatadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    tag: {{ .Values.image.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: zengzhiyuan/articles-service-core:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - ConfigMapRef:
                name: common-rabbit
            - ConfigMapRef:
                name: common-mysql
            - SecretRef:
                name: common
      restartPolicy: Always